language: node_js
node_js:
  - "9"
dist: trusty
sudo: false

branches:
  only:
  - master
before_script:
  -yarn global add @angular/cli
cache:
  directories:
    - node_modules

install:
  - npm install -g yarn

script:
  - ng build --prod --base-href https://hsdesigns.github.io/MEAN-SNS/
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./dist/
  on:
    branch: master